spring.application.name=digital-slambook

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/slambook1
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CORS
# ===============================
cors.allowed-origins=http://localhost:5173

# ===============================
# Supabase Storage
# ===============================
supabase.url=${SUPABASE_URL}
supabase.service-key=${SUPABASE_SERVICE_KEY}